"""
Centralized embedding service for Agent Suite.

This module provides a shared interface for generating embeddings using
various models, with Cohere as the default implementation.
"""

import os
from typing import List, Dict, Any, Optional, Union
import logging
from functools import lru_cache

import numpy as np
from dotenv import load_dotenv
import cohere

# Load environment variables for API keys
load_dotenv()

logger = logging.getLogger(__name__)


class EmbeddingService:
    """
    Service for generating embeddings from text.
    
    This class provides an interface for generating embeddings using
    different models, with Cohere as the default implementation.
    """
    
    def __init__(
        self,
        model_name: str = "embed-english-v3.0",
        api_key: Optional[str] = None,
        input_type: str = "search_document"
    ):
        """
        Initialize the embedding service.
        
        Args:
            model_name: Name of the embedding model to use
            api_key: API key for the embedding service (if not in env)
            input_type: Type of embedding to generate 
                        (search_document, search_query, classification, clustering)
        """
        self.model_name = model_name
        self.input_type = input_type
        
        # Get API key from params or environment
        self.api_key = api_key or os.getenv("COHERE_API_KEY")
        
        if not self.api_key:
            raise ValueError(
                "Cohere API key not provided. Set COHERE_API_KEY environment variable or pass as api_key."
            )
        
        # Initialize the client
        self.client = cohere.Client(api_key=self.api_key)
        
        # Store vector dimensions for common models
        self.vector_dimensions = {
            "embed-english-v3.0": 1024,
            "embed-english-light-v3.0": 384,
            "embed-multilingual-v3.0": 1024,
            "embed-multilingual-light-v3.0": 384
        }
    
    def get_vector_size(self) -> int:
        """
        Get the vector size for the current model.
        
        Returns:
            Dimension of vectors generated by the model
        """
        return self.vector_dimensions.get(self.model_name, 1024)
    
    @lru_cache(maxsize=100)
    def _embed_single(self, text: str) -> List[float]:
        """
        Generate embedding for a single text (with caching).
        
        Args:
            text: Text to embed
            
        Returns:
            Embedding vector
        """
        try:
            response = self.client.embed(
                texts=[text],
                model=self.model_name,
                input_type=self.input_type
            )
            
            # Return the first embedding (only one text provided)
            return response.embeddings[0]
        except Exception as e:
            logger.error(f"Error generating embedding: {str(e)}")
            # Return a zero vector of appropriate size as fallback
            return [0.0] * self.get_vector_size()
    
    def embed(self, texts: Union[str, List[str]]) -> List[List[float]]:
        """
        Generate embeddings for text(s).
        
        Args:
            texts: Single text string or list of text strings
            
        Returns:
            List of embedding vectors
        """
        # Handle single text case
        if isinstance(texts, str):
            return [self._embed_single(texts)]
        
        # Handle empty list
        if not texts:
            return []
        
        # For small batches, use cached single embedding function
        if len(texts) <= 3:
            return [self._embed_single(text) for text in texts]
        
        # For larger batches, use batch API
        try:
            # Split into chunks of 96 (Cohere limit)
            batch_size = 96
            all_embeddings = []
            
            for i in range(0, len(texts), batch_size):
                batch = texts[i:i+batch_size]
                response = self.client.embed(
                    texts=batch,
                    model=self.model_name,
                    input_type=self.input_type
                )
                all_embeddings.extend(response.embeddings)
            
            return all_embeddings
            
        except Exception as e:
            logger.error(f"Error generating batch embeddings: {str(e)}")
            # Fallback to cache-enabled single embeddings
            return [self._embed_single(text) for text in texts]
    
    def embed_query(self, query: str) -> List[float]:
        """
        Generate embedding specifically for a search query.
        
        Args:
            query: Search query text
            
        Returns:
            Embedding vector
        """
        # Save current input type
        original_input_type = self.input_type
        
        try:
            # Set to query mode
            self.input_type = "search_query"
            
            # Generate embedding
            return self._embed_single(query)
            
        finally:
            # Restore original input type
            self.input_type = original_input_type
    
    def embed_documents(self, documents: List[str]) -> List[List[float]]:
        """
        Generate embeddings specifically for documents.
        
        Args:
            documents: List of document texts
            
        Returns:
            List of embedding vectors
        """
        # Save current input type
        original_input_type = self.input_type
        
        try:
            # Set to document mode
            self.input_type = "search_document"
            
            # Generate embeddings
            return self.embed(documents)
            
        finally:
            # Restore original input type
            self.input_type = original_input_type 